### PR TITLE
[pytorch] Disable pytorch for nnstreamer @open sesame 05/22 10:50

### PR DESCRIPTION
**Pull request by kparichay**
Disable pytorch for nnstreamer in yocto

**Self evaluation:**
1. Build test: [ ]Passed [ ]Failed [*]Skipped
2. Run test: [ ]Passed [ ]Failed [* ]Skipped

Signed-off-by: Parichay Kapoor <pk.kapoor@samsung.com>

### CODE REVIEW

**Comment by wooksong** [comment]
@kparichay This PR itself looks good me, but is it possible to work without merging https://github.com/nnsuite/nnstreamer/pull/1447?

**Comment by kparichay** [comment]
> @kparichay This PR itself looks good me, but is it possible to work without merging [nnsuite/nnstreamer#1447](https://github.com/nnsuite/nnstreamer/pull/1447)?

This should give a warning of unknown options, but I think it should not fail the build.
With the implementation, nnsuite/nnstreamer#1447 cannot pass the all the checks without disabling the pytorch for yocto. If this PR does not work, I will modify nnsuite/nnstreamer#1447 to merge first.

**Comment by wooksong** [comment]
> > @kparichay This PR itself looks good me, but is it possible to work without merging [nnsuite/nnstreamer#1447](https://github.com/nnsuite/nnstreamer/pull/1447)?
> 
> This should give a warning of unknown options, but I think it should not fail the build.
> With the implementation, [nnsuite/nnstreamer#1447](https://github.com/nnsuite/nnstreamer/pull/1447) cannot pass the all the checks without disabling the pytorch for yocto. If this PR does not work, I will modify [nnsuite/nnstreamer#1447](https://github.com/nnsuite/nnstreamer/pull/1447) to merge first.

@kparichay Acked.

**Comment by myungjoo** [comment]
There is no reason to block this PR due to trivial false-positives from CI system. Thus, I'm merging this.

**Pull request merged**
