### PR TITLE
Add tensorflow-lite recipe for version 1.15.2. @open sesame 2/07 12:17

### PR DESCRIPTION
**Pull request by bairyn**
Adds tensorflow-lite_1.15.2.bb.

### CODE REVIEW

**Comment by myungjoo** [comment]
It looks like your commit fails to build (```TAOS/pr-audio-build-yocto``` --> ```report``` --> ```build_log_46_bitbake_yocto_error.txt```)

I would like the commit to have signed-off as well.

@wooksong When it passes the build-test, please review this.

**Comment by wooksong** [comment]
@bairyn Please fill the body of your commit and append the `Signed-off-by` tag also.

CC: @myungjoo I checked that it is possible to build TF-Lite 1.15.2 with the recipe suggested in this PR.

**Comment by myungjoo** [comment]
Please add Signed-off-by so that we can release binaries including yours:

(from Linux kernel documentation):
```
11) Sign your work - the Developer's Certificate of Origin
----------------------------------------------------------

To improve tracking of who did what, especially with patches that can
percolate to their final resting place in the kernel through several
layers of maintainers, we've introduced a "sign-off" procedure on
patches that are being emailed around.

The sign-off is a simple line at the end of the explanation for the
patch, which certifies that you wrote it or otherwise have the right to
pass it on as an open-source patch.  The rules are pretty simple: if you
can certify the below:

Developer's Certificate of Origin 1.1
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

By making a contribution to this project, I certify that:

        (a) The contribution was created in whole or in part by me and I
            have the right to submit it under the open source license
            indicated in the file; or

        (b) The contribution is based upon previous work that, to the best
            of my knowledge, is covered under an appropriate open source
            license and I have the right under that license to submit that
            work with modifications, whether created in whole or in part
            by me, under the same open source license (unless I am
            permitted to submit under a different license), as indicated
            in the file; or

        (c) The contribution was provided directly to me by some other
            person who certified (a), (b) or (c) and I have not modified
            it.

        (d) I understand and agree that this project and the contribution
            are public and that a record of the contribution (including all
            personal information I submit with it, including my sign-off) is
            maintained indefinitely and may be redistributed consistent with
            this project or the open source license(s) involved.

then you just add a line saying::

        Signed-off-by: Random J Developer <random@developer.example.org>

using your real name (sorry, no pseudonyms or anonymous contributions.)
```

**Comment by bairyn** [comment]
I rebased on upstream/master and amended my commit with the "-s" signoff flag.

**Pull request merged**
